---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cowsay-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cowsay-server
    spec:
      containers:
      - name: cowsay-server
        image: gcr.io/k8s-demos-142718/github-gke-deploy-demo-cowsay-server:167255a6476204b7aa14d22bf76ea63988477371
        ports:
        - containerPort: 80
