---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: cowsay-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cowsay-server
    spec:
      containers:
      - name: cowsay-server
        image: gcr.io/k8s-demos-142718/github-gke-deploy-demo-cowsay-server:b7c6194631f1cc6430e62f92aa5f437b5431b323
        ports:
        - containerPort: 80
